add(web-apps): i18n Fr translations
kubeflow/kubeflow pull request #6122
Opened 2021-09-07 15:49 UTC by rohank07

This PR adds i18n localize FR translations.
Related to #5858

Translates all crud-web-apps/jupyter/frontend literals in French.
To test this feature:
`ng serve --configuration=fr`

2021-09-07 16:04 UTC, rohank07 commented
@googlebot I fixed it.

2021-09-09 10:13 UTC, kimwnasptd commented
Thanks for updating the translation files @rohank07! I'll wait for @wg102 or @Jose-Matsuda to also take a glance at this.

/lgtm

2021-09-09 18:14 UTC, wg102 requested changes
A few request of change for the French translations.

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>LAUNCH</target>
LANCER

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Aucun stockage par default n'est définie. Impossible de créer un nouveau disque pour le nouveau bloc-notes. Veuillez utiliser un disque existant.</target>
Aucune classe de stockage par défaut n'est définie. Impossible de créer un nouveau disque pour le nouveau bloc-notes. Veuillez utiliser un disque existant.

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>GPU</target>
GPUs

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Nombre GPUs</target>
Nombre de GPUs

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Une image Jupyter Docker de démarrage avec un déploiement de base et typique Paquets ML</target>
Une image Jupyter Docker de démarrage avec un déploiement de base et les paquets ML typiques

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Télécharge l'image</target>
Politique de téléchargement de l'image

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Si elle n'est pas présente</target>
Is this used as a value? In which case it probably needs to stay IfNotPresent. Otherwise the translation is valid.

2021-09-09 18:14 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/i18n/fr/messages.fr.xlf
> +        <target>Votre espace de travail ne sera pas persistant. Toutes les données seront perdues si le bloc-notes est terminé, pour quelque raison que ce soit.</target>
Votre espace de travail ne sera pas persistant. Toutes les données seront perdues si le bloc-notes prend fin, pour quelque raison que ce soit.

2021-09-17 14:54 UTC, wg102 approved these changes

2021-09-17 14:55 UTC, wg102 commented
Translations fixed
/lgtm 
/approve

2021-09-17 18:02 UTC, rohank07 commented
/retest

2021-09-22 13:52 UTC, wg102 commented
/ok-to-test

2021-11-18 14:04 UTC, rohank07 commented
/retest

2021-11-18 14:23 UTC, kimwnasptd commented
@rohank07 could you try to rebase your branch on top of the latest master and force push? This could help with the failing tests

2021-11-24 15:25 UTC, rohank07 commented
@kimwnasptd Can you please approve? Thanks.

2021-11-24 15:28 UTC, kimwnasptd commented
Thanks for the work @rohank07!

/lgtm
/approve

2021-11-24 15:29 UTC, merged