[Profile controller IAM plugin] Support annotation only
kubeflow/kubeflow pull request #6887
Opened 2023-01-11 08:36 UTC by ryansteakley

AWS IAM service account profile plugin mutates the trust relationship in the iam role specified in the spec. 

Customers have different ways to manage roles and their company policies might not allow Kubeflow profile controller to allow changing the trust relationship. 

Adding a boolean variable to the AwsIAMForServiceAccount struct to enable users to specify if they want AnnotateOnly which will cause IAM roles and policy will not be mutated.

This change will not effect existing users who do not have the boolean field in their yaml files.

2023-01-12 16:38 UTC, kimwnasptd commented
If it's good from AWS' side, since it only touches this functionality, I'm good with merging this

2023-01-12 19:40 UTC, surajkota requested changes
looks good, can you add a unit test?

2023-01-12 19:40 UTC, surajkota commented on components/profile-controller/controllers/plugin_iam.go
> +		logger.Info("DisableAutoUpdateIAM set to true IAM roles and policy will not be mutated")
AnnotateOnly set to true

2023-01-16 10:13 UTC, kimwnasptd commented
Thanks for your time @ryansteakley @surajkota!

/lgtm
/approve

2023-01-16 10:15 UTC, merged

2023-01-16 21:10 UTC, surajkota commented
Thanks